baseurl         = "https://matthias-kraft.github.io"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Matthias Kraft"
  subtitle    = "Making mission-critical AI safe with Lakera. "
  description = "Personal blog on AI, software engineering and mission-critical systems."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  logo = ""

  linkedinName = "matthias-kraft-5b1229a1"
  githubName = "matthias-kraft"

  author = "Matthias Kraft"
  authorAvatar = "/image/cartoon_mk.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://www.linkedin.com/in/matthias-kraft-5b1229a1/"
  authorDescription = "I’m a founder of Lakera AI where we are enabling mission-critical Artifical Intelligence."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
